export const APP_STORE_ARTIFACT_KEYS = [
  "PRIVACY_POLICY",
  "TERMS_OF_SERVICE",
  "ACCOUNT_DELETION",
  "SUPPORT_CONTACT",
  "REVIEWER_DEMO",
  "APP_ICONS",
  "SPLASH",
  "PERMISSIONS"
] as const;
